server:
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/crypto/api/v1}
spring:
  application:
    name: crypto-recommender
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Crypto provider configuration
crypto:
  csv:
    directory: ${CRYPTO_CSV_DIRECTORY:prices}

resilience4j:
  ratelimiter:
    instances:
      recominderConntroller: # todo: it is not IP based , will be for all clients, implement IP based rate limiting better on Gateway level(via Spring Cloud Gateway , API Gateway, Nginx, etc.)
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: false
        eventConsumerBufferSize: 100